# Generated by Django 4.2.4 on 2023-09-21 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_todo_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="date",
        ),
    ]
