version: '3'

services:

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./db.sqlite3:/home/dev/dcrm (copy)/dcrm/db.sqlite3


